name: Go Spec Checks

on:
    workflow_dispatch:
    schedule:
      - cron: "0 0 * * *"
permissions:
  contents: read
  actions: read
  checks: write
jobs:
  test:
    uses: ./.github/workflows/template.yaml
    with:
      name: Gno VM
      run-command: '-count=1 -v ./... -args -run-cmd="gno run {path} -root-dir ./gno"'
      need-extra-binaries: true
      extra-binaries-install: |
                      git clone https://github.com/gnolang/gno.git
                      cd gno/gnovm
                      make install