name: Go Spec Checks

on:
    workflow_dispatch:
    schedule:
      - cron: "0 0 * * *"
permissions:
  contents: read
  actions: read
  checks: write
jobs:
  test:
    uses: ./.github/workflows/template.yaml
    with:
      name: Go
      run-command: '-count=1 -v ./... -args -run-cmd="go run {path}"'
      need-extra-binaries: false