on:
    workflow_call:
      inputs:
        run-command:
          required: true
          type: string
        name:
          required: true
          type: string
        extra-binaries-install:
          required: false
          type: string
        need-extra-binaries:
          required: true
          type: boolean
permissions:
  contents: read
  actions: read
  checks: write
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.21' ]
    steps:
    - uses: actions/checkout@v4
    - name: Setup Go ${{ matrix.go-version }}
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}
    - name: Install Prerequisites (${{inputs.name}})
      if: ${{inputs.need-extra-binaries}}
      run: ${{inputs.extra-binaries-install}}
    - name: Install gotestsum (${{inputs.name}})
      run: go install gotest.tools/gotestsum@latest
    - name: Set up gotestfmt (${{inputs.name}})
      run: go install github.com/gotesttools/gotestfmt/v2/cmd/gotestfmt@latest

    - name: Execute gotestsum (${{inputs.name}})
      run: gotestsum --format testname --junitfile junit-tests-output.xml --jsonfile test-output.json -- ${{inputs.run-command}}
    - name: Pretty Test Output
      run: cat test-output.json | gotestfmt
    - name: Test Report (${{inputs.name}})
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: ${{inputs.name}} Spec Coverage
        path: junit-*.xml
        reporter: java-junit
        fail-on-error: 'false'
        max-annotations: '45'
