on:
    workflow_call:
      inputs:
        run-command:
          required: true
          type: string
        name:
          required: true
          type: string
        extra-binaries-install:
          required: false
          type: string
        need-extra-binaries:
          required: true
          type: boolean
permissions:
  contents: read
  actions: read
  checks: write
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.21' ]
    steps:
    - uses: actions/checkout@v4
    - name: Setup Go ${{ matrix.go-version }}
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}
    - name: Install Prerequisites (${{inputs.name}})
      if: ${{inputs.need-extra-binaries}}
      run: ${{inputs.extra-binaries-install}}
    - name: Install gotestreport (${{inputs.name}})
      run: go install github.com/becheran/go-testreport@latest
    - name: Execute gotestreport (${{inputs.name}})
      run:  go test -json ${{inputs.run-command}} | go-testreport $GITHUB_STEP_SUMMARY