name: Yaegi Spec Checks

on:
    workflow_dispatch:
    schedule:
      - cron: "0 0 * * *"
permissions:
  contents: read
  actions: read
  checks: write
jobs:
  test:
    uses: ./.github/workflows/template.yaml
    with:
      name: Yaegi
      run-command: '-count=1 -v ./... -args -run-cmd="yaegi run -unsafe {path}"'
      need-extra-binaries: true
      extra-binaries-install: go install github.com/traefik/yaegi/cmd/yaegi@latest
